stages:
  - test
  - deploy

# This job is only executed in feature branches, so it is possible to check the
# generated files via the job artefacts before a merge into the default branch.
test:
  image: registry.gitlab.com/kamapu/quarto-image:1.3.361-0
  script:
    - quarto render . --output-dir=public/
  artifacts:
    paths:
      - public/
  rules:
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH

pages:
  image: registry.gitlab.com/kamapu/quarto-image:1.3.361-0
  script:
    - quarto render . --output-dir=public/
  artifacts:
    paths:
      - public/
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
